name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci

      - name: Disable CSS optimization in Next.js config
        run: |
          sed -i 's/optimizeCss: true/optimizeCss: false/g' next.config.js
          cat next.config.js

      - name: Install critters globally
        run: npm install -g critters@0.0.20

      - name: Build with direct script
        run: node scripts/build-direct.js
        env:
          NEXT_PUBLIC_BASE_PATH: /travel-places
          NEXT_DISABLE_OPTIMIZED_CSS: "true"
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
